export const Portfolio_Data = [
  {
    id: 1,
    image: "./images/p1.jpg",
    name: "Spectranomy",
    url1:"	https://ftechiz.com/wp-content/uploads/2022/08/spectranomy.jpg",
    category: "WEBSITE",
  },
  {
    id: 2,
    image: "./images/p2.jpg",
    name: "Authoreon",
    url1:"	https://ftechiz.com/wp-content/uploads/2022/08/authoreon.jpg",
    category: "WEBSITE",
  },
  {
    id: 3,
    image: "./images/p3.jpg",
    name: "Rara Delivery",
    url1:"https://ftechiz.com/wp-content/uploads/2022/08/rara_delivery.jpg",
    category: "WEBSITE",
  },
  {
    id: 4,
    image: "./images/p4.jpg",
    name: "Fork Coin",
    url1:"https://ftechiz.com/wp-content/uploads/2022/08/forkcoin.jpg",
    category: "WEBSITE",
  },
  {
    id: 5,
    image: "./images/p5.jpg",
    name: "Advancity",
    url1:"	https://ftechiz.com/wp-content/uploads/2022/08/Advancity.jpg",
    category: "WEBSITE",
  },
  {
    id: 6,
    image: "./images/p6.jpg",
    name: "a2zpc",
    url1:"	https://ftechiz.com/wp-content/uploads/2022/08/a2zpc.jpg",
    category: "WEBSITE",
  },
  {
    id: 7,
    image: "./images/p7.jpg",
    name: "Decokay",
    url1:"https://ftechiz.com/wp-content/uploads/2022/08/decokay.jpg",
    category: "WEBSITE",
  },
  {
    id: 8,
    image: "./images/p8.jpg",
    name: "Hire Military",
    url1:"https://ftechiz.com/wp-content/uploads/2022/08/hire_military.jpg",
    category: "WEBSITE",
  },
  {
    id: 9,
    image: "./images/p9.jpg",
    name: "Etherscan",
    url1:"	https://ftechiz.com/wp-content/uploads/2022/08/etherscan.jpg",
    category: "WEBSITE",
  },
  {
    id: 10,
    image: "./images/p10.jpg",
    name: "Etherscan",
    url1:"https://ftechiz.com/wp-content/uploads/2022/08/etherscan_2.jpg",
    category: "MOBILE APPLICATION",
  },
  {
    id: 11,
    image: "./images/p11.jpg",
    name: "My Mountains",
    url1:"	https://ftechiz.com/wp-content/uploads/2022/08/myMointains.jpg",
    category: "WEBSITE",
  },

  {
    id: 12,
    image: "./images/p12.jpg",
    name: "Gearstream",
    url1:"	https://ftechiz.com/wp-content/uploads/2022/08/gearstream.jpg",
    category: "WEBSITE",
  },
  {
    id: 13,
    image: "./images/p13.jpg",
    name: "One Code",
    url1:"https://ftechiz.com/wp-content/uploads/2022/08/gearstream.jpg",
    category: "WEBSITE",
  },
  {
    id: 14,
    image: "./images/p14.jpg",
    name: "Trajecutive",
    url1:"	https://ftechiz.com/wp-content/uploads/2022/08/trajecutive.jpg",
    category: "WEBSITE",
  },
  {
    id: 15,
    image: "./images/p15.jpg",
    name: "Digicel PlayGo",
    url1:"https://ftechiz.com/wp-content/uploads/2022/08/Digicel-PlayGo-1.jpg",
    category: "WEBSITE",
  },
  {
    id: 16,
    image: "./images/p16.jpg",
    name: "Silent Beacon",
    url1:"	https://ftechiz.com/wp-content/uploads/2022/08/Silent-Beacon-1.jpg",
    category: "MOBILE APPLICATION",
  },
  {
    id: 17,
    image: "./images/p17.jpg",
    name: "Cryptopocket",
    url1:"	https://ftechiz.com/wp-content/uploads/2022/08/Cryptopocket-1.jpg",
    category: "MOBILE APPLICATION",
  },
  {
    id: 18,
    image: "./images/p18.jpg",
    name: "Defix Wallet",
    url1:"https://ftechiz.com/wp-content/uploads/2022/08/Defix-Wallet-1.jpg",
    category: "MOBILE APPLICATION",
  },
  {
    id: 19,
    image: "./images/p19.jpg",
    name: "360 Notes",
    url1:"https://ftechiz.com/wp-content/uploads/2022/08/360Notes-1.jpg",
    category: "MOBILE APPLICATION",
  },
];
